sudo: required

language: node_js
node_js:
  - "lts/*"

services:
  - docker

before_script:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - docker-compose up -d

script:
  - npm test

after_script:
  - docker-compose down
