name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-feature:
    permissions:
      actions: read
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start docker containers
        run: docker compose up --build -d postgres

      - name: Install dependencies
        run: |
          npm install -g npm@11.12.1
          npm ci
        env:
          NODE_ENV: "test"
      - name: Run tests
        run: npx c8 --reporter=none mocha --exit --reporter=dot

      - name: Check coverage
        run: |
          npx c8 report --skip-full
          npx c8 check-coverage

      - name: Check linting
        run: npx eslint .

      - name: Check dependencies
        run: npx knip --dependencies --reporter github-actions
